import {
  blackAdidas,
  blackBallenciaga,
  blackLouboutin,
  blackLv,
  blackNB,
  blackNike,
  discount1,
  discount2,
  discount3,
  discount4,
  newArrival1,
  newArrival2,
  newArrival3,
  newArrival4,
  newArrival5,
  newArrival6,
  newArrival7,
  offer1,
  offer2,
  offer3,
  offer4,
  offer5,
  offer6,
  skechers,
  underArmor,
} from "../assets";

export const newArrival = [
  {
    id: 0,
    name: "Louis Vuitton “Trainer Snowboot”",
    image: newArrival1,
    logo: blackLv,
    category: "Sneakers",
    color: "Brown",
    price: 430000,
    logoSize: { width: "40px", height: "40px" },
  },
  {
    id: 1,
    name: "Nike Air Max 1 “Panda”",
    image: newArrival2,
    logo: blackNike,
    category: "Sneakers",
    color: "White",
    price: 350000,
    logoSize: { width: "60px", height: "25px" },
  },
  {
    id: 2,
    name: "Women’s Knife Knot “Pump”",
    image: newArrival3,
    logo: blackBallenciaga,
    category: "Heels",
    color: "Pink",
    price: 550000,
    logoSize: { width: "150px", height: "35px" },
  },
  {
    id: 3,
    name: "Nike Calm “Panda”",
    image: newArrival4,
    logo: blackNike,
    category: "Men’s Slides",
    color: "Black",
    price: 50000,
    logoSize: { width: "60px", height: "25px" },
  },
  {
    id: 4,
    name: "Gazelle Indoor",
    image: newArrival5,
    logo: blackAdidas,
    category: "Shoe",
    color: "Red",
    price: 400000,
    logoSize: { width: "60px", height: "40px" },
  },
  {
    id: 5,
    name: "Christian Louboutin “Chambeliss Night”",
    image: newArrival6,
    logo: blackLouboutin,
    category: "Men’s buckles",
    color: "Wine",
    price: 1350000,
    logoSize: { width: "100px", height: "50px" },
  },
  {
    id: 6,
    name: "Women’s Knife",
    image: newArrival7,
    logo: blackBallenciaga,
    category: "Heels",
    color: "Black",
    price: 330000,
    logoSize: { width: "150px", height: "35px" },
  },
];

export const discountOffer = [
  {
    id: 0,
    name: "Alpharesponse 2.0 Slides",
    image: discount1,
    logo: blackAdidas,
    category: "Slides",
    color: "Blue",
    discount: "10% OFF",
    price: 50000,
    logoSize: { width: "60px", height: "40px" },
  },
  {
    id: 2,
    name: "Louis Vuitton “LV Cherry pump”",
    image: discount2,
    logo: blackLv,
    category: "Heels",
    color: "Brown",
    discount: "10% OFF",
    price: 330000,
    logoSize: { width: "40px", height: "40px" },
  },
  {
    id: 3,
    name: "Louis Vuitton “Chelsea Boot”",
    image: discount3,
    logo: blackLv,
    category: "Sneakers",
    color: "Black",
    discount: "5% OFF",
    price: 430000,
    logoSize: { width: "40px", height: "40px" },
  },
  {
    id: 4,
    name: "MEN'S RUNNER SNEAKER",
    image: discount4,
    logo: blackBallenciaga,
    category: "Sneakers",
    color: "White",
    discount: "10% OFF",
    price: 500000,
    logoSize: { width: "150px", height: "35px" },
  },
];

export const offers = [
  {
    id: 0,
    name: "Men's Runner Sneaker",
    image: offer1,
    logo: skechers,
    category: "Sneakers",
    price: 70000,
    logoSize: { width: "150px", height: "40px" },
  },
  {
    id: 1,
    name: "Women’s UA Stellar Tactical Boots",
    image: offer2,
    logo: underArmor,
    category: "Boots",
    price: 95000,
    logoSize: { width: "40px", height: "40px" },
  },
  {
    id: 2,
    name: "Louis Junior Spikes",
    image: offer3,
    logo: blackLouboutin,
    category: "Sneakers",
    price: 325000,
    logoSize: { width: "100px", height: "50px" },
  },
  {
    id: 3,
    name: "Men’s Stomper Bootie",
    image: offer4,
    logo: blackBallenciaga,
    category: "Boots",
    price: 415000,
    logoSize: { width: "150px", height: "35px" },
  },
  {
    id: 4,
    name: "1906R",
    image: offer5,
    logo: blackNB,
    category: "Sneaker",
    price: 98000,
    logoSize: { width: "150px", height: "25px" },
  },
  {
    id: 5,
    name: "Nike Air Max 270",
    image: offer6,
    logo: blackNike,
    category: "Women Shoe",
    price: 98000,
    logoSize: { width: "60px", height: "25px" },
  },
];
